Use Fish Data set and perform Naive Bayes Classification to predict species of Fish 

Take Species as Target Variable 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("Fish.csv")

In [3]:
df

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [4]:
df.insert(0, 'ID', range(1, 1 + len(df)))
df.set_index("ID",inplace=True)

In [5]:
df

Species  Weight  Length1  Length2  Length3   Height   Width
ID                                                             
1     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
2     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
3     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
4     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
5     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
155   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
156   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
157   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
158   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
159   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 159 entries, 1 to 159
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 9.9+ KB


In [7]:
df.columns

Index(['Species', 'Weight', 'Length1', 'Length2', 'Length3', 'Height',
       'Width'],
      dtype='object')

In [8]:
# ml will not take character based values so lets perform 
# label encoding on given feature and target 
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
Species_encoded=le.fit_transform(df['Species'])
'''
Weight_encoded=le.fit_transform(df['Weight'])
Length1_encoded=le.fit_transform(df['Length1'])
Length2_encoded=le.fit_transform(df['Length2'])
Length3_encoded=le.fit_transform(df['Length3'])
Height_encoded=le.fit_transform(df['Height'])
Width_encoded=le.fit_transform(df['Width'])'''

"\nWeight_encoded=le.fit_transform(df['Weight'])\nLength1_encoded=le.fit_transform(df['Length1'])\nLength2_encoded=le.fit_transform(df['Length2'])\nLength3_encoded=le.fit_transform(df['Length3'])\nHeight_encoded=le.fit_transform(df['Height'])\nWidth_encoded=le.fit_transform(df['Width'])"

In [9]:
Species_encoded

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5])

In [11]:
x=df.drop("Species",axis=1)
y=Species_encoded

In [13]:
# import required modules 
from sklearn.linear_model import LinearRegression 
from sklearn.model_selection import train_test_split

In [14]:
#test Train model
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=1)

In [15]:
# Model Training 
lr=LinearRegression() # object will be created
# llearning model on given data 
# use theta0+theta1x to calculate bestfit prediction line 
lr.fit(x_train,y_train)

LinearRegression()

In [16]:
# now model is trained and ready to predict 
# but before we use it for prediction let's check it's accuracy 
y_pred=lr.predict(x_test)

In [17]:
y_test # x_test original   y
y_pred # prediction x_test yhat 

# MSE = sum((y-yhat)**2)/n 

array([-1.13764887,  3.36162504,  0.26944684,  2.6207865 ,  2.39776362,
        1.12188568,  3.05826387,  0.4679833 ,  2.72706798,  2.39773574,
        2.57183474,  3.07142562,  3.5332504 ,  2.28361994,  2.31956382,
        3.06284135,  1.61697107,  2.65623262,  2.31902094,  2.47492502,
        4.4912489 ,  3.99931407,  3.13100523,  0.31505216,  2.80208128,
       -1.00653141,  0.68086294,  4.76837261,  3.74343462,  2.59052702,
        2.19535043,  2.22624708,  3.10409501,  2.64453347,  2.59583519,
        2.12155199,  3.6162448 ,  0.84024841, -1.56513275,  2.18992413,
        2.66152441,  2.08222238,  1.66428712,  4.64269582,  0.27005482,
        2.12835775,  3.22017082, -0.12055295])

In [18]:
y_test

array([0, 4, 0, 2, 2, 0, 4, 0, 4, 2, 2, 2, 2, 2, 6, 2, 1, 4, 2, 2, 5, 4,
       4, 0, 2, 0, 0, 5, 3, 2, 2, 2, 2, 3, 6, 2, 4, 1, 0, 6, 3, 2, 2, 5,
       0, 2, 2, 0])

In [19]:
from sklearn.metrics import mean_squared_error 
from sklearn.metrics import r2_score

In [20]:
mse=mean_squared_error(y_test,y_pred)
r2score=r2_score(y_test,y_pred)
print(" accuracy MSE is {} ".format(mse))
print(" accuracy R2 score is {} ".format(r2score))

 accuracy MSE is 1.3307482513548878 
 accuracy R2 score is 0.5522716163665798 


In [29]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,test_size=0.3)
gnb=GaussianNB()
gnb.fit(x_train,y_train)

GaussianNB()

In [30]:
y_pred=gnb.predict(x_test)

In [31]:
from sklearn.metrics import classification_report

In [32]:
# it give recall,precision,negative classification rate ,positive classification rate,Accuracy 
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.71      1.00      0.83        10
           1       0.33      0.50      0.40         2
           2       0.88      0.35      0.50        20
           3       0.67      0.67      0.67         3
           4       0.31      0.71      0.43         7
           5       1.00      1.00      1.00         3
           6       0.00      0.00      0.00         3

    accuracy                           0.58        48
   macro avg       0.56      0.60      0.55        48
weighted avg       0.68      0.58      0.57        48



In [33]:
# i want to find how much records are mis classified in wine naivebayes ml model 
print(x_test.shape)

(48, 6)


In [34]:
(y_test != y_pred).sum()

20